name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2022-08-17
version: '9.5.x-dev'
project: 'drupal'
datestamp: 1660735355
