name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2022-08-17
version: '9.5.x-dev'
project: 'drupal'
datestamp: 1660735355
